name: CI

on:
  workflow_dispatch:

jobs:
  testing-runner:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4

      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          az --version
          Write-Host ""
          bicep --version
          Write-Host ""
          pwsh --version
          Write-Host ""
          Get-Module 
          Get-Module -ListAvailable
          Write-Host ""
          gci env:
