name: Print runner data

on:
  workflow_dispatch:

jobs:
  print-runner-data:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4

      - name: Print data from the runner
        shell: pwsh
        run: |
          az --version
          Write-Host ""
          bicep --version
          Write-Host ""
          pwsh --version
          Write-Host ""
          Get-Module -ListAvailable
          Write-Host ""
          Get-ChildItem env: | Select-Object Name, Value
